name: Release and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PKG_AUTH_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Check for existing tag
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists. Skipping tag creation."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create Tag
        if: env.TAG_EXISTS == 'false'
        id: create_tag
        run: |
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
          echo "Tag created: v${{ env.VERSION }}"

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Check for existing release
        id: check_release
        run: |
          if gh release view "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Release v${{ env.VERSION }} already exists. Skipping release creation."
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create Release
        if: env.RELEASE_EXISTS == 'false'
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "v${{ env.VERSION }}" --title "Release v${{ env.VERSION }}" --notes "Release notes for version v${{ env.VERSION }}" --generate-notes